CPPFLAGS = -DUSE_CLOCK -Ofast -msse -march=native -fopenmp
transform_image: io.o transfo.o
	$(CC) -Ofast -march=native -msse -fopenmp -o $@ $^
io.o: transfo.h
clean:
	rm -f *.o transform_image
	rm -fr cmake-build-debug
